### ISSUE TITLE
3a.  Conservation Landscape:  Same Fields as rain garden/bioswales:

### ISSUE THREAD

**Issue by rdawes1** [viableindustries/WatershedStewardsAcademy-CleanWaterCommunities#13]
WSA wants to add:

i.	Length
ii.	Width
iii.	Area draining to practice
iv.	% of area draining to practice that is impervious
v.	Ponding depth – set to zero (0) [this is Bryan’s suggestion]
vi.	Filter depth – set default as 12 (or another number) and allow for adjustment, as in the rain garden/bioswale practice

**Comment by joshuapowell** [comment]
The new fields have been added. We created a new Credit Calculation layer for the Conservation Landscape as well.
