### ISSUE TITLE
Downspouts 1a-c.

### ISSUE THREAD

**Issue by rdawes1** [viableindustries/WatershedStewardsAcademy-CleanWaterCommunities#9]
a.     How does the number of downspouts currently hook into Bryan's algorithm? 
b.	Wouldn’t you really only want to enter the number of downspouts you’d planned to disconnect and/or connect to a rain barrel rather than the total number of downspouts?
c.	I feel like we’ve lost the connection between downspout disconnections and rain barrels that was there in the previous version of the calculator. If it is there, perhaps we need to be a bit more explicit about it.

**Comment by rdawes1** [comment]
Just a comment but we are under the impression that with our new work, downspouts go away.  This also points the fact that the calculations really need to be written up by Bryan at CWP.

**Comment by joshuapowell** [comment]
Rain barrels and downspouts stay as is, no further changes.
